# 02-virtualmachine.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine

metadata:
  name: {{ .VmName }}
  namespace: {{ .Namespace }}
  labels:
    kite.anacnu.com/managed-by: kite-controller
    kite.anacnu.com/kite-vm-name: {{ .VmName }}
    kite.anacnu.com/kite-vm-namespace: {{ .Namespace }}

spec:
  runStrategy: {{ .RunStrategy }}
  template:
    metadata:
      labels:
        kite.anacnu.com/managed-by: kite-controller
        kite.anacnu.com/kite-vm-name: {{ .VmName }}
        kite.anacnu.com/kite-vm-namespace: {{ .Namespace }}
    spec:
      domain:
        resources:
          requests: { memory: {{ .Memory }}, cpu: {{ .CPU }} }
        devices:
          disks:
            - name: rootdisk
              disk: { bus: virtio }
            - name: cloudinitdisk
              disk: { bus: virtio }
      volumes:
        - name: rootdisk
          dataVolume: { name: {{ .VmName }}-disk }
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: {{ .VmName }}-cloud-init-userdata
