apiVersion: v1
kind: ResourceQuota
metadata:
  name: kite-user-quota-policy
  namespace: {{ .Namespace }}

spec:
  hard:
    requests.cpu: "6"
    requests.memory: 5Gi
    persistentvolumeclaims: "5"
    count/virtualmachines.kubevirt.io: "3"
