apiVersion: v1
kind: ResourceQuota
metadata:
  name: kite-user-quota-policy
  namespace: {{ .Namespace }}

spec:
  hard:
    requests.cpu: "4"
    requests.memory: 2Gi
    persistentvolumeclaims: "5"
    count/virtualmachines.kubevirt.io: "2"
