apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume

metadata:
  name: {{ .VmName }}-disk
  namespace: {{ .Namespace }}
  labels:
    kite.anacnu.com/managed-by: kite-controller
    kite.anacnu.com/kite-vm-name: {{ .VmName }}
    kite.anacnu.com/kite-vm-namespace: {{ .Namespace }}

spec:
  source:
    pvc:
      name: {{ .VmImage }}
      namespace: kite

  pvc:
    {{ if .StorageClassName }}
    storageClassName: {{ .StorageClassName }}
    {{ end }}
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: {{ .Storage }}
