apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume

metadata:
  name: ubuntu-22.04
  namespace: kite

spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"

  pvc:
    accessModes: ["ReadWriteOnce"]

    # 추후, kite CRD에 storageClassName을 넣거나 사용자가 적도록 변경 가능한 ui를 제공해야합니다.
    #storageClassName: local-path

    resources:
      requests:
        storage: 4Gi
