apiVersion: anacnu.com/v1 # CRD의 group과 version
kind: KiteVirtualMachine # CRD의 names.kind

metadata:
  name: test-kite-vm # 생성할 리소스의 이름
  namespace: test # scope가 Namespaced이므로 네임스페이스 지정
spec: # CRD의 spec에 정의한 속성들
  cpu: 2
  memory: "4Gi"
  image: "ubuntu-22.04"
  disk: "4Gi"
