package guestlogin

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"strings"

	"github.com/GehirnInc/crypt"
	_ "github.com/GehirnInc/crypt/sha512_crypt"
)

const (
	// PasswordHashKey is the Secret data key that stores the VM OS login hash.
	// The API writes this value and the controller reads it before rendering cloud-init.
	PasswordHashKey = "passwordHash"
)

const (
	passwordHashRounds = 500000
	passwordSaltLength = 16
	passwordSaltChars  = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
)

// SecretName returns the guest login Secret name for one KiteVirtualMachine.
// vmName is the KiteVirtualMachine metadata.name.
// The returned name is used by kite-api when writing the Secret and by kite-controller when reading it.
func SecretName(vmName string) string {
	return strings.TrimSpace(vmName) + "-guest-login"
}

// GeneratePasswordHash creates a Linux SHA-512 crypt hash for VM console login.
// password is the plain text VM creation password from the API request and is not stored.
// The returned string is suitable for cloud-init hashed_passwd and /etc/shadow compatible logins.
// This function is used by the VM create flow before writing the guest login Secret.
func GeneratePasswordHash(password string) (string, error) {
	salt, err := randomSalt()
	if err != nil {
		return "", err
	}

	saltPrefix := fmt.Sprintf("$6$rounds=%d$", passwordHashRounds)
	hashed, err := crypt.New(crypt.SHA512).Generate([]byte(password), []byte(saltPrefix+salt))
	if err != nil {
		return "", fmt.Errorf("generate Linux guest password hash: %w", err)
	}

	return hashed, nil
}

// VerifyPasswordHash checks a password against a Linux SHA-512 crypt hash.
// password is the candidate plain text value.
// hash is the stored crypt hash generated by GeneratePasswordHash.
// A true return means the hash matches and can authenticate the VM OS account.
// This function is used by tests to verify the guest login hash contract.
func VerifyPasswordHash(password string, hash string) bool {
	return crypt.New(crypt.SHA512).Verify(hash, []byte(password)) == nil
}

func randomSalt() (string, error) {
	var builder strings.Builder
	builder.Grow(passwordSaltLength)

	max := big.NewInt(int64(len(passwordSaltChars)))
	for i := 0; i < passwordSaltLength; i++ {
		index, err := rand.Int(rand.Reader, max)
		if err != nil {
			return "", fmt.Errorf("generate Linux guest password salt: %w", err)
		}
		builder.WriteByte(passwordSaltChars[index.Int64()])
	}

	return builder.String(), nil
}
