apiVersion: v1
kind: Service

metadata:
  name: vps-access-{{ .VmName }}
  namespace: {{ .Namespace }}
  labels:
    hy3ons.github.io/managed-by: kite-controller
    hy3ons.github.io/kite-vm-name: {{ .VmName }}
    hy3ons.github.io/kite-vm-namespace: {{ .Namespace }}

spec:
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: {{ .VmName }}
  ports:
    - port: 22
      targetPort: 22

---
apiVersion: v1
kind: Service
metadata:
  name: vps-web-{{ .VmName }}
  namespace: {{ .Namespace }}
  labels:
    hy3ons.github.io/managed-by: kite-controller
    hy3ons.github.io/kite-vm-name: {{ .VmName }}
    hy3ons.github.io/kite-vm-namespace: {{ .Namespace }}
spec:
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: {{ .VmName }}
  ports:
    - port: 80
      targetPort: 80
